-- This file should undo anything in `up.sql`

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

DROP SCHEMA IF EXISTS `BPI` ;

DROP TABLE IF EXISTS `Payments`;

DROP TABLE IF EXISTS `Bet` ;

DROP TABLE IF EXISTS `UserData` ;

DROP TABLE IF EXISTS `Run` ;

DROP TABLE IF EXISTS `CompetList` ;

DROP TABLE IF EXISTS `Horses` ;

DROP TABLE IF EXISTS `Owners` ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;