-- Your SQL goes here
-- MySQL Script generated by MySQL Workbench
-- Чтв 06 фев 2020 13:15:25
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema BPI
-- -----------------------------------------------------


-- -----------------------------------------------------
-- Schema BPI
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BPI` DEFAULT CHARACTER SET utf8mb4 ;
SHOW WARNINGS;
USE `BPI` ;

-- -----------------------------------------------------
-- Table `Owners`
-- -----------------------------------------------------


SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Owners` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  `Surname` VARCHAR(45) NULL DEFAULT NULL,
  `Age` INT(11) NULL DEFAULT NULL,
  `UUID` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Horses`
-- -----------------------------------------------------


SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Horses` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  `Owner` INT(11) NULL DEFAULT NULL,
  `Age` INT(11) NULL DEFAULT NULL,
  `WinRate` DOUBLE NULL DEFAULT NULL,
  `RunsDone` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`),
  CONSTRAINT `Horses`
    FOREIGN KEY (`Owner`)
    REFERENCES `Owners` (`ID`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `Horses` ON `Horses` (`Owner` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `CompetList`
-- -----------------------------------------------------


SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `CompetList` (
  `Run_compet` INT(11) NOT NULL,
  `HorseID` INT(11) NOT NULL,
  PRIMARY KEY (`Run_compet`, `HorseID`),
  CONSTRAINT `fk_CompetListH`
    FOREIGN KEY (`HorseID`)
    REFERENCES `Horses` (`ID`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_CompetListH` ON `CompetList` (`HorseID` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Run`
-- -----------------------------------------------------


SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Run` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Date` DATE NULL DEFAULT NULL,
  `Place` VARCHAR(50) NULL DEFAULT NULL,
  `Winner` INT(11) NULL DEFAULT NULL,
  `CompetitorsList` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_RunComp`
    FOREIGN KEY (`CompetitorsList`)
    REFERENCES `CompetList` (`Run_compet`),
  CONSTRAINT `fk_Run_Horses1`
    FOREIGN KEY (`Winner`)
    REFERENCES `Horses` (`ID`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_RunComp` ON `Run` (`CompetitorsList` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_Run_Horses1_idx` ON `Run` (`Winner` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `UserData`
-- -----------------------------------------------------


SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `UserData` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Login` VARCHAR(45) NULL DEFAULT NULL,
  `Passwh` BINARY(128) NULL DEFAULT NULL,
  `UserType` ENUM('Admin', 'User', 'Guest') NULL DEFAULT 'Guest',
  `Credits` INT(11) NULL DEFAULT NULL,
  `Balance` DOUBLE NOT NULL DEFAULT '0',
  `AssocInf` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `Credits` ON `UserData` (`Credits` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Bet`
-- -----------------------------------------------------


SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Bet` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Who` INT(11) NULL DEFAULT NULL,
  `Value` DOUBLE NULL DEFAULT NULL,
  `on_run` INT(11) NULL DEFAULT NULL,
  `on_winner` INT(11) NULL DEFAULT NULL,
  `win_rate` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `Bet`
    FOREIGN KEY (`on_run`)
    REFERENCES `Run` (`ID`),
  CONSTRAINT `fk_bet_usr`
    FOREIGN KEY (`Who`)
    REFERENCES `UserData` (`ID`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `Bet` ON `Bet` (`on_run` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_bet_usr` ON `Bet` (`Who` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Payments`
-- -----------------------------------------------------


SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Payments` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Other_side` INT(11) NULL DEFAULT NULL,
  `Value` INT(11) NULL DEFAULT NULL,
  `Outcoming` TINYINT(1) NULL DEFAULT NULL,
  `State` ENUM('Pending', 'Rejected', 'Done') NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_user`
    FOREIGN KEY (`Other_side`)
    REFERENCES `UserData` (`Credits`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_user` ON `Payments` (`Other_side` ASC);

SHOW WARNINGS;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
